populateDefaultValues(false);
addSalaryUpdateListener();
addHoverModeUpdateListener();
addDisableForThisSiteUpdateListener();
addDisableExtensionListener();
addColourCodePriceListener();
addPercentageModeListener();
addResultUpdateListener();
addBudgetUpdateListener();