# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
          mkdir test_report
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test ci
    - name: zip unpacked extension
      if: always()
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r affordable.mihir src
    - name: Send failed test report
      if: always()
      uses: dawidd6/action-send-mail@v3  
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: Affordable Tests Failure Report
        # email body as text
        body: Attachments of this email (if any) are the screenshots for tests which failed to run. Filenames indicate the website for which it failed.
        # comma-separated string, send email to
        to: mihir67mj@gmail.com
        # from email name
        from: Github Workflow
        attachments: ./test_report/*.png,affordable.mihir

